trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m unittest test.py
  displayName: 'Run Tests'

- script: |
    docker build -t mywebserver .
  displayName: 'Build Docker Image'
